### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by devWaleed** [feature23/StringSimilarity.NET#13]
I added the package using command and it was installed succesfully. But I can't use any of the classes. Reference is properly added as I can add F23 packages on top of namespace but can't use any class like StringProfile or KShingLing

I am on .NET 4.5 or something (not .net core)

EDIT:

I can use some of the classes like QGram. I am not actualy doing any code, just copying snippets to test but its giving error on KShingling. I want to use Cosine Similarity method.

**Comment by kitsu** [comment]
Per #10 the KShingLing class was removed. Looking at the [Java version docs](https://github.com/tdebatty/java-string-similarity#shingle-n-gram-based-algorithms) it looks like it was renamed `Cosine`. (Note their docs also still reference KShingLing)

**Comment by paulirwin** [comment]
Sorry for the delay on this, but @kitsu is correct, it was renamed to Cosine. I've updated the README to match.
