### ISSUE TITLE
Jaro-Winkler compare strings with 2 and 3 chars

### ISSUE THREAD

**Issue by RNGIllSkillz** [feature23/StringSimilarity.NET#30]
`
var l = new JaroWinkler();
Console.WriteLine(l.Similarity("!EZ", "EZ"));
`
will print 0

**Comment by paulirwin** [comment]
@RNGIllSkillz I was able to confirm that the upstream [java-string-similarity](https://github.com/tdebatty/java-string-similarity) library that this code is based upon produces the same result. I'm not sure this is entirely a bug; `!EZ` and `EZ` are indeed dissimilar. If you feel this behavior is incorrect, please file a bug at the upstream library. Thanks!
