### ISSUE TITLE
Supporting comparisons using `byte[]`

### ISSUE THREAD

**Issue by RenderMichael** [feature23/StringSimilarity.NET#35]
I want to use this library but I have data as `byte[]`.

Would it be possible to add support for `ReadOnlySpan<byte>` as well as `string`? In fact, there's probably room for tons of optimizations if the algorithms take `ReadOnlySpan<T>` which would be ROS<char> for string inputs

**Comment by RenderMichael** [comment]
Thanks for the reply @paulirwin! Actually we have a system comparing two `Stream`s for equality, within a given tolerance. so we pull out the `byte[]` from the Stream, and it would be optimal for us to compare those bytes directly. Currently we map to a `char[]` with `Encoding.Latin1.GetString()` because `Latin1` has a 1-to-1 mapping between char <-> byte.

Your concern about UTF8-encoding is completely correct, and any ByteSimilarity implementation would have to make those caveats clear. 

Another think I realized is the library targets .NET standard 2.0, which would make a lot of this challenging. .NET 7 introduced lots of support for generic math, which would make a `byte` implementation share almost all (maybe all?) code with a `char` version. I.E. both `byte` and `char` implement the interface `IBinaryInteger<TSelf> where TSelf : IBinaryInteger<TSelf>`. 

That doesn't lend itself well to multi-targeting, since you would basically have two versions of the same code, at which point it might as well be 2 libraries.

**Comment by paulirwin** [comment]
That makes sense, thank you. Perhaps we might start with just a single algorithm rather than doing it for all of them upfront. Do you have a specific similarity algorithm that you'd use that could be a good first test case for this?

**Comment by RenderMichael** [comment]
We default to the `Damerau` algorithm, but switch to `Levenshtein` for the occasional huge input (if you think there's a better one to choose for our purposes please let me know! I'm no expert in the details here).

Thanks for considering this!

**Comment by RenderMichael** [comment]
@paulirwin I like it!

One thing though, is there any way the `ReadOnlySpan<T>` methods could constrain `T : IEquatable<T>`? I see there's `s1 == s2` between two ROS's, which tests identity rather than the same contents.

The usual way to test ROS content equality is `s1.SequenceEqual(s2)` but that requires the above constraint. It would also optimize the `T.Equals(object)` method by automatically rerouting to `T.Equals(T)`, which prevents boxing. 

The previous implementation using string required an explicit conversion to a `char[]` but `ROS<T>` is automatically `T[]`-like, so in `LongestCommonSubsequence` the `s1.ToCharArray()` which was converted to `s1.ToArray()` are no longer necessary, and `s1` can be used as is.

Thanks for the effort!

**Comment by paulirwin** [comment]
Great catches all around, thank you. I think I've fixed all of them. Take a look at the branch or the PR for it and let me know what you think. https://github.com/feature23/StringSimilarity.NET/pull/36

**Comment by RenderMichael** [comment]
@paulirwin Sorry for the long delay, kids are kids.

The contents of the PR look really nice! I tested `Damerau` and `Levenshtein`, the two algorithms I've been using. No performance regressions compared to the main branch. Goodness all around.

**Comment by RenderMichael** [comment]
@paulirwin The work in the associated PR looks great, any chance it could be merged?

**Comment by paulirwin** [comment]
@RenderMichael v6.0.0 has been released to NuGet. Please let me know if you have any issues. Thanks!
